export default Object.freeze({
    SET_TASKS: "SET_TASKS",
    DELETE_ONE_TASK: "DELETE_ONE_TASK",
    SET_OR_REMOVE_LOADING: "SET_OR_REMOVE_LOADING",
    SET_DELETE_TASK_ID: "SET_DELETE_TASK_ID",
    TOGGLE_OPEN_ADD_TASK_MODAL: "TOGGLE_OPEN_ADD_TASK_MODAL",
    ADD_TASK: "ADD_TASK",
    TOGGLE_CONFIRM_MODAL: "TOGGLE_CONFIRM_MODAL",
    TOGGLE_CHECK_TASK: "TOGGLE_CHECK_TASK",
    DELETE_CHECKED_TASKS: "DELETE_CHECKED_TASKS",
    TOGGLE_CHECK_ALL: "TOGGLE_CHECK_ALL"
});