export default Object.freeze({
    //GLOBAL TYPES
    SET_OR_REMOVE_LOADING: "SET_OR_REMOVE_LOADING",
    SET_ERROR_MESSAGE: "SET_ERROR_MESSAGE",
    SET_SUCCESS_MESSAGE: "SET_SUCCESS_MESSAGE",
    //TODO TYPES
    SET_TASKS: "SET_TASKS",
    DELETE_ONE_TASK: "DELETE_ONE_TASK",
    SET_DELETE_TASK_ID: "SET_DELETE_TASK_ID",
    TOGGLE_OPEN_ADD_TASK_MODAL: "TOGGLE_OPEN_ADD_TASK_MODAL",
    ADD_TASK: "ADD_TASK",
    TOGGLE_CONFIRM_MODAL: "TOGGLE_CONFIRM_MODAL",
    TOGGLE_CHECK_TASK: "TOGGLE_CHECK_TASK",
    DELETE_CHECKED_TASKS: "DELETE_CHECKED_TASKS",
    TOGGLE_CHECK_ALL: "TOGGLE_CHECK_ALL",
    SET_EDIT_TASK: "SET_EDIT_TASK",
    EDIT_TASK: "EDIT_TASK",
    RESET_DATA: "RESET_DATA",
    //SINGLETASK TYPES
    SET_SINGLE_TASK: "SET_SINGLE_TASK",
    TOGGLE_SINGLETASK_EDIT_MODAL: "TOGGLE_SINGLETASK_EDIT_MODAL",
    RESET_SINGLE_TASK_STATE: "RESET_SINGLE_TASK_STATE",

    //CONTACT TYPES
    CHANGE_CONTACT_FORM: "CHANGE_CONTACT_FORM"


});